global:
  scrape_interval: 10s  # Intervalo padrão de coleta de métricas
  evaluation_interval: 5s  # Intervalo padrão para avaliação de regras

scrape_configs:
  # Monitoramento do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoramento do MySQL Exporter
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']  # Nome corrigido para corresponder ao serviço no docker-compose

  # Monitoramento da aplicação Flask
  - job_name: 'flask_app_exporter'
    static_configs:
      - targets: ['flask-container:5000']

